### ISSUE TITLE
GROUNDED flags table (R20) needs updating and expanding

### ISSUE THREAD

**Issue by matdon17** [nvs-vocabs/R20#1]
At ADMT-21, a proposal to update R20 to include revised definitions for some existing entries and the addition of new terms was approved.  Primary contact is Megan Scanderbeg.

**Comment by vpaba** [comment]
New edits in page 98-99 of manual: https://archimer.ifremer.fr/doc/00187/29825/80869.pdf
R20 currently: https://vocab.nerc.ac.uk/collection/R20/current/ 

Suggested NVS implementation (Identifier | PrefLabel | Definition) :

- Y | Grounded, and free-drift period affected | Yes, the float touched the ground and   the programmed free-drift period was affected. If it is uncertain what mission phase the grounding took place, use ‘Y’.
- P | Grounded, but free-drift period not affected | Yes, the float touched the ground during a part of the mission that did not affect the free-drift period.
- B | Grounded (external bathymetry database check), and free-drift period affected | Yes, the float touched the ground as determined by an external bathymetry database and the programmed free-drift period was affected. If it is uncertain what mission phase the grounding took place, use ‘B’.
- C | Grounded (external bathymetry database check), but free-drift period not affected | Yes, the float touched the ground as determined by an external bathymetry database during a part of the mission that did not affect the free-drift period.
- N | Not grounded | No, the float did not touch the ground

Also, is it confirmed that the S and U codes are to be deprecated?

Waiting for feedback from AVTT editors.

**Comment by mscanderbeg** [comment]
Thanks for working on adding the updates to the Grounded ref table to the NVS Argo vocab collection.  I agree with the addition of the 'PrefLabel' wording.
I admit I was not aware of the suggestions to deprecate the S and U codes and I'm not sure of the implications of a deprecated vocab.  Will there still be a link to the deprecated codes from the R20 table in case traj files have them still?

 I agree that U and fill value are similar, but we would need to change the recommendation for DACs to use 'U' in real time and instead use fill value.  To me, this is something that could be suggested in the next round of file format changes, but not worth asking DACs to rewrite the trajectory files for at this point.  So, for now, I think it would be best not to deprecate U.  

I'm not sure how useful the 'S' flag is anymore as most floats now return regular pressure measurements during drift.  If it only applies to older floats, should it be deprecated or still listed in the table?

**Comment by matdon17** [comment]
I wasn't aware of the S or U suggestions either.

Deprecated codes (concepts) on the NVS are still visible, but they are simply listed as 'deprecated', e.g. for examples search for 'deprecated' on P07: 
http://vocab.nerc.ac.uk/collection/P07/current/

Or view a particular deprecated code, where the value of deprecated is 'true':
http://vocab.nerc.ac.uk/collection/P07/current/CFSN0012/

My view is that if it is in the current data system, then it should be retained unless and until we can phase it out.  The deprecated status could be used to underpin warnings initially, and eventually errors in the file checkers.  We will need to manage the data from even the oldest floats in perpetuity, so whatever the decision it should be applied retroactively.

**Comment by vpaba** [comment]
Thanks very much @matdon17 and @mscanderbeg for your replies.

R20 has been updated - please note it may take up to 24h for the edits to show on the NVS interface.

I have not deprecated the U and S codes, as further discussion is needed around the latest suggestion in the Argo User Manual to declare them 'obsolete'.
